name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Run API tests
      run: ./gradlew test --tests "*ApiTestRunner"

    - name: Run Web tests
      run: ./gradlew test --tests "*WebTestRunner"

    - name: Upload Cucumber reports
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: build/reports/cucumber/